
# "Out of the box", Instiki stores it's data in sqlite3 database. Other options are listed below.

development:
    adapter: sqlite3
    database: db/development.db

test:
    adapter: sqlite3
    database: db/test.db.sqlite3

production:
  adapter: sqlite3
  database: db/production.db.sqlite3
  
# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   There is no gem for Windows.  Install mysql.so from RubyForApache.
#   http://rubyforge.org/projects/rubyforapache
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html


# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

mysql_example:
  adapter: mysql
  database: instiki_development
  username: root
  password:
  socket: /path/to/your/mysql.sock

# Connect on a TCP socket.  If omitted, the adapter will connect on the
# domain socket given by socket instead.
#host: localhost
#port: 3306
  
# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
mysql_example:
  adapter: mysql
  database: instiki_test
  username: root
  password:
  socket: /path/to/your/mysql.sock

# PostgreSQL versions 7.4 - 8.2
#
# Get the C bindings:
#   gem install postgres
# or use the pure-Ruby bindings (the only know way on Windows):
#   gem install postgres-pr

postgresql_example:
  adapter: postgresql
  database: instiki_development
  username: instiki
  password:

  # Connect on a TCP socket.  Omitted by default since the client uses a
  # domain socket that doesn't need configuration.
  #host: remote-database
  #port: 5432

  # Schema search path.  The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Character set encoding.  The server defaults to sql_ascii.
  #encoding: UTF8

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   info, notice, warning, error, log, fatal, or panic
  # The server defaults to notice.
  #min_messages: warning


# SQLite version 2.x
#   gem install sqlite-ruby
sqlite_example:
  adapter: sqlite
  database: db/development.sqlite2


# SQLite version 3.x
#   gem install sqlite3-ruby
sqlite3_example:
  adapter: sqlite3
  database: db/development.sqlite3

# In-memory SQLite 3 database.  Useful for tests.
sqlite3_in_memory_example:
  adapter: sqlite3
  database: ":memory:"
